# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:pBjqQQaUmw==,iv:X016x87gwBW37rlMmLWi0T+7V5GxooUNgdxnN3D4fOY=,tag:9EQy3sxlFp2tR7vd9ddJgQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DK68O7Jyeh1M5gGk,iv:+UmV3l/B9ONttVBLDz2VTZR1egy6lK/VtEO8oUElNlU=,tag:dIYB0dN4mo1jrHlQa1adiA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:BjqkeApp+jhUDTgbqABwb7q6W5gLig0qGwDuah7eD5xuCSCYJDl9Zg==,iv:o0vw+nnvKdxtSQVBZ0MmdRlIGZ+hNsoJYAWAnYSjVos=,tag:/5CIlO4Es1IZ2Kb+MWFWKA==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:+bxcFxNBg38j,iv:7PMu7ji2k4+f6o/XZdY3VjqpNcitEujMnmZiZUset+s=,tag:f6eSGCTJNN56F9rVDSRYZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-18T22:41:51Z"
    mac: ENC[AES256_GCM,data:Ak0ul/G4b3/K+Oqq1pttbI8/Qf2oDaJD6jqfKFBIVnxjXhK4h9ar2GPY/yckhIJvyp8N1q/UNzUURd2qrC1/5om9I5FE4cUb7XfCvTKZQb1YXE3R/QB9ajqeg/geJ1ymtdOFneyrVfK/uWMEK7Vzbk+URnVelSG4+HL528WR2To=,iv:beg3l37LjZo7ySpaFtT4dVV+dNEfwogU5qkQ40NEfQg=,tag:VOyXD6/Dl52qIzEEIXEOxw==,type:str]
    pgp:
        - created_at: "2021-05-18T22:41:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7RADZALL4rUARAAhPZ9DRj4xPprRoiLLfXCwNTTL1ihdy1bwBeIGiYwtioE
            wk233kJzwFVRVVbIDgNt1UD90te9iXyq34Id9rJzuQPSI+jqFFdKAuk9/ljzJSPF
            a73vog3Se1Q8wLDwyMU8H0yILhQSqcvCf+iMHKkT53GbTio+ppPTDh4rEwcFui5K
            U26+R4ulCl1OW6f/oc84cKQxbq7BJQ1wEeJBKOqxOw9aBHfvWgtG7/jaa2nYavwG
            Ng7mgc/qdm7I3Obtu8wwO5tp5x37NG0+tuQlyJ5zWNGBcqqYPa8ycolZgpTvM7BV
            3ZBai2GR+D0qsxi5LIa5UTyDIskXYd8nvAFa/lxZ5XspCV2G5kz5vtEBMLxd1vy8
            3TJvHWDmTQcUxC6FrzluecN6h0qfF4kGdH5mT4h0GSpBgSG7nq+YHRWe54iiRR6q
            1rVyHlQzB5/0RDKEKI4G/qXyJYCK/S+mYSYD+9HClKCD6rthifhdNR7j7wG+wnP3
            hG61+JMHdAFOEm2hdr8Umi122YZnMdUlyEub8smt2VbhceV8JJ3vXSAFOrZ/cdJP
            NuXc7YCSu4edZOANK38gBKmR4vO8MG4cTaH5xDgOTttoZRuUFiw5YQ+KZ7TKRtFY
            i8PQ78/c6XVMY8QY9ytRw5O861eFMmrvD3JJwr5A7nA9lw4Dkwia/llipJmXkoTS
            XAF4jG/sIszzuwYz09Agx9cQUeDABhnhtvsAQWVcIOlFkbBR8xmMxEOiSJ2cIGzh
            uV9ht6JPN0GdrivxoaCqewUeyK67WYEk6toJfUIuSJFYYiAeGEHsXPEHCDbQ
            =iQfF
            -----END PGP MESSAGE-----
          fp: 967B58590229B9D7B20AF5DA5DFA8AE4EDE33854
        - created_at: "2021-05-18T22:41:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3bBzfM8OoteARAAvDp2qPU94AW8TB/EO3hbc7b7rg1HYjitZB2HsTk/Hr9i
            ToyxgcC1enIgVl+WF54nSOUlPrkiYBPyEsX3qoYxxKt8EAufJCi9W85pM6B8cggC
            IEzdConQ8My+Cn4NoLG9EOnyyXon0HAV2us6EIR19YwbdiWLxMbcGq4Sm1mOjj4/
            /OzG86kTWPpYxj/dAbpp0iGS7+MnINAO4E1GaIqolNJkWZrL5WTS6aiA2zg+OVPw
            Jd0Qo+b53HTUz2CzQEngN63udqj3Ith7ARvu03AcPnRtzmGACmLI6rktkJq8huOS
            QiIldQKWo9iF1CZ2E9/G0JfO7oQU6dfFDrnhELH1uMz9LThFdNk9Y0aj6RCxa+g9
            v3OBUX4zWTozCLleTK2DXI/WOE9Q42JtDftXL0w1owpK/d3EZOpa2LFMza+eP7Lc
            7lb2h+m0HMoKZsdEtdwn1nUrRM/uHYtO9tJfjVkKntB5DUAS/fh9j5+mc9e9hH0s
            pT9Itg186VskroDYegF7aWd0xBUIjojfFBMNbZnwS1/G8/ZL7wEQFwETvRTGtEbF
            6JI5eEjk+uRnRb7/rNSAJw+PyQM4htduJfGBzZtMerbUml+evlJ5pt1peKWvhSKH
            8N72zFAodzDxGy+3L10hlubSM9oFk6+ZYCDAawM/mOcw/sQriRLqBtrRr6rlvlLS
            XAF1Ua/nVVBTAdIO1tsA2eLKZdLsVg/cTZum4EQm6LQnqBpOB+L3sV28mHYUKrp+
            UVgiGCNIPKzGuob4kqwPj5z7WV4+PVaiQiDhr3mxR7t5az/kCyicbE3Y8HYY
            =jZJY
            -----END PGP MESSAGE-----
          fp: 99DA48B3EBBC6060DDEB5D9E66E0D89FBC799E0B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
